### ISSUE TITLE
Overlay is displayed even when no data is sent

### ISSUE THREAD

**Issue by baarsik** [kOFReadie/BeatSaber-Overlay#1]
Overlay displays sample data even when Beat Saber is offline and no data is sent.

**Comment by kOFReadie** [comment]
I don't see how this is an issue, it is meant to do that, as BeatSaber is closed it cannot update the UI, if you would like I can make it so that the UI hides when BS is closed

**Comment by baarsik** [comment]
That would help a lot. I will explain why this is an issue. If you set this as a source and try to stream another game, you have to manually disable this source or switch the scene, which is quite irritating.

**Comment by kOFReadie** [comment]
Ok, I’ll work on it tomorrow, quite tired right now. As for the scenes thing I don’t know why you wouldn’t just have multiple scenes setup with automatic scene switcher enabled.

**Comment by kOFReadie** [comment]
I've added the option to hide the UI when the game is closed using the URL modifier ?hideInactive
