### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by Protheus23** [kOFReadie/BeatSaber-Overlay#2]
I think i'm to dumb to use the Options.
Where must i insert the Options to activate? (Overlay in OBS is active (but not shown in 16:9))

I want the Overlay in the upper left corner. Is there a Overlay too?

Greets

**Comment by kOFReadie** [comment]
## Streaming Overlay
Sorry this is a late reply, I've been working on other projects. Assuming your using OBS make sure the resolution of the source is set to a 16:9 format e.g. 1920x1080
![image](https://user-images.githubusercontent.com/60425965/84625671-ac4cb300-aedb-11ea-99ff-d9713d4fec56.png)  
  
## URL Parameters
As for the URL parameters for the first one you would put the URL and then a question mark (?) followed by the argument name and if required value, to separate values use the & symbol e.g.
These URL params [http://kofreadie.globalgamingco.org/?moveBSR&scale=1.5&flip](http://kofreadie.globalgamingco.org/?moveBSR&scale=1.5&flip) would result in this:
![image](https://user-images.githubusercontent.com/60425965/84625909-12d1d100-aedc-11ea-9a99-c28cf58d30e0.png)

**Comment by kOFReadie** [comment]
Glancing over your comment where you said:  
> I want the Overlay in the upper left corner. Is there a Overlay too?  
For now I have only implemented the option to have the map information be to the bottom left (default) or bottom right, if you want to have it at the top then I will have to implement that

**Comment by kOFReadie** [comment]
Glancing over your comment where you said; `I want the Overlay in the upper left corner. Is there a Overlay too?`  
For now I have only implemented the option to have the map information be to the bottom left (default) or bottom right, if you want to have it at the top then I will have to implement that

**Comment by Protheus23** [comment]
Hi,
 Thanks for the reply.
i'll try the options this evening.
Yes i want it in the upper left corner (like HTTPStatus was) (picture). It would be nice to have it :)
![Screenshot - 2020-06-15 14_09_05-Saufen morgens, mittags, abends mp4 - Daum PotPlayer](https://user-images.githubusercontent.com/60545975/84655834-f781b880-af11-11ea-8393-fd89d3402b31.png)

**Comment by kOFReadie** [comment]
It is done @Protheus23 read how to use it [here](github.com/kOFReadie/BeatSaber-Overlay/blob/master/README.md#flip), if you have any more issues with it DM me on discord.
